#ifndef DISPLAY_H
#define DISPLAY_H

// Базовые адреса:
#define DISPLAY_CLEAR 0x01
#define DISPLAY_RETURNHOME 0x02
#define DISPLAY_ENTRYMODESET 0x04
#define DISPLAY_CONTROL 0x08
#define DISPLAY_SHIFT 0x10
#define DISPLAY_FUNCTIONSET 0x20
#define DISPLAY_SETCGRAMADDR 0x40
#define DISPLAY_SETDDRAMADDR 0x80

// Битовые маски для Entry Mode Set (0x04):
#define DISPLAY_DISPLAYSHIFTOFF 0x00
#define DISPLAY_DISPLAYSHIFTON 0x01
#define DISPLAY_ENTRYSHIFTDECREMENT 0x00 // Влево.
#define DISPLAY_ENTRYSHIFTINCREMENT 0x02 // Вправо.

// Битовые маски для Display ON/OFF Control (0x08):
#define DISPLAY_BLINKOFF 0x00
#define DISPLAY_BLINKON 0x01
#define DISPLAY_CURSOROFF 0x00
#define DISPLAY_CURSORON 0x02
#define DISPLAY_DISPLAYOFF 0x00
#define DISPLAY_DISPLAYON 0x04

// Битовые маски для Cursor or Display Shift (0x10):
#define DISPLAY_SHIFTLEFT 0x00
#define DISPLAY_SHIFTRIGHT 0x04
#define DISPLAY_CURSORMOVE 0x00
#define DISPLAY_DISPLAYMOVE 0x08

// Битовые маски для Function Set (0x20):
#define DISPLAY_5x8DOTS 0x00
#define DISPLAY_5x11DOTS 0x04
#define DISPLAY_1LINE 0x00
#define DISPLAY_2LINE 0x08
#define DISPLAY_4BITMODE 0x00
#define DISPLAY_8BITMODE 0x10

// Готовые команды:
#define DISPLAY_CMD_4BIT_2LINE_5x8 (DISPLAY_FUNCTIONSET | DISPLAY_4BITMODE | DISPLAY_2LINE | DISPLAY_5x8DOTS)
#define DISPLAY_CMD_DISPLAY_ON (DISPLAY_CONTROL | DISPLAY_DISPLAYON | DISPLAY_CURSOROFF | DISPLAY_BLINKOFF)
#define DISPLAY_CMD_DISPLAY_OFF (DISPLAY_CONTROL | DISPLAY_DISPLAYOFF)
#define DISPLAY_CMD_ENTRY_RIGHT (DISPLAY_ENTRYMODESET | DISPLAY_ENTRYSHIFTINCREMENT | DISPLAY_DISPLAYSHIFTOFF)

void Display_Init(void);
void Display_Clear(void);
void Display_PrintString(const char* str);

#endif